import { useEffect, useState } from "react";
import { CalendarClock, LogIn, Save, Settings2, RotateCcw, ShieldCheck, Trophy, RadioTower } from "lucide-react";
import toast from "react-hot-toast";
import { getAssessmentSettings, updateAssessmentSettings } from "../assessmentApi";
import type { Assessment } from "../AssessmentCard";

interface Props { assessment: Assessment; }
interface SettingsState { schedule:{startDate:string;startTime:string;endDate:string;endTime:string;duration:number}; rules:{randomQuestions:boolean;randomOptions:boolean}; results:{passingPercentage:number}; login:{authentication:"PASSWORD"|"OTP"}; live:{enabled:boolean}; }
const defaults:SettingsState={schedule:{startDate:"",startTime:"",endDate:"",endTime:"",duration:30},rules:{randomQuestions:true,randomOptions:true},results:{passingPercentage:40},login:{authentication:"PASSWORD"},live:{enabled:true}};
const localDateTime=(value?:string|null)=>{if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;};
const toIso=(date:string,time:string)=>date&&time?new Date(`${date}T${time}:00`).toISOString():null;

export default function Settings({assessment}:Props){
 const [settings,setSettings]=useState<SettingsState>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=async()=>{try{setLoading(true);const data=await getAssessmentSettings(assessment.id);const incoming=data||{};setSettings({...defaults,...incoming,schedule:{...defaults.schedule,...incoming.schedule,duration:Number(incoming.schedule?.duration??assessment.duration_minutes??30)},rules:{...defaults.rules,...incoming.rules},results:{passingPercentage:Number(incoming.results?.passingPercentage??assessment.pass_percentage??40)},login:{authentication:incoming.login?.authentication==="OTP"?"OTP":"PASSWORD"},live:{enabled:incoming.live?.enabled!==false&&assessment.live_updates_enabled!==false}});}catch(e){console.error(e);toast.error("Unable to load settings.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[assessment.id]);
 const save=async()=>{try{setSaving(true);if(!settings.schedule.startDate||!settings.schedule.startTime||!settings.schedule.endDate||!settings.schedule.endTime)return toast.error("Start and end date/time are required.");const start=toIso(settings.schedule.startDate,settings.schedule.startTime)!;const end=toIso(settings.schedule.endDate,settings.schedule.endTime)!;if(new Date(end)<=new Date(start))return toast.error("End time must be after start time.");if(settings.schedule.duration<1)return toast.error("Duration must be at least 1 minute.");if(settings.results.passingPercentage<0||settings.results.passingPercentage>100)return toast.error("Passing percentage must be between 0 and 100.");await updateAssessmentSettings(assessment.id,{schedule:{startDate:settings.schedule.startDate,startTime:settings.schedule.startTime,endDate:settings.schedule.endDate,endTime:settings.schedule.endTime,startIso:start,endIso:end,duration:Number(settings.schedule.duration)},rules:settings.rules,results:settings.results,login:settings.login,live:settings.live});localStorage.setItem(`assessment_live_updates:${assessment.id}`,String(settings.live.enabled));window.dispatchEvent(new CustomEvent("assessment-live-updates-changed",{detail:{assessmentId:assessment.id,enabled:settings.live.enabled}}));window.dispatchEvent(new CustomEvent("assessment-data-changed"));toast.success("Settings saved successfully.");await load();}catch(e:any){console.error(e);toast.error(e?.response?.data?.message||"Unable to save settings.");}finally{setSaving(false);}};
 if(loading)return <div className="rounded-2xl border bg-white py-24 text-center text-slate-500">Loading Settings...</div>;
 const setSchedule=(key:keyof SettingsState["schedule"],value:string|number)=>setSettings(s=>({...s,schedule:{...s.schedule,[key]:value}}));
 return <div className="space-y-6"><div className="flex flex-col gap-4 rounded-2xl border bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#00629B]">Configuration</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Assessment Settings</h2><p className="mt-1 text-sm text-slate-500">Schedule, login, live updates and result rules.</p></div><div className="flex gap-3"><button type="button" onClick={()=>void load()} className="rounded-xl border p-3 text-slate-600"><RotateCcw size={18}/></button><button type="button" onClick={()=>void save()} disabled={saving} className="flex items-center gap-2 rounded-xl bg-[#00629B] px-5 py-3 font-semibold text-white disabled:opacity-50"><Save size={18}/>{saving?"Saving...":"Save Changes"}</button></div></div>
 <Section icon={<CalendarClock size={21}/>} title="Schedule & Duration" description="Set the official start/end window and attempt duration."><div className="grid gap-5 md:grid-cols-2"><Field label="Start Date"><input type="date" value={settings.schedule.startDate} onChange={e=>setSchedule("startDate",e.target.value)}/></Field><Field label="Start Time"><input type="time" value={settings.schedule.startTime} onChange={e=>setSchedule("startTime",e.target.value)}/></Field><Field label="End Date"><input type="date" value={settings.schedule.endDate} onChange={e=>setSchedule("endDate",e.target.value)}/></Field><Field label="End Time"><input type="time" value={settings.schedule.endTime} onChange={e=>setSchedule("endTime",e.target.value)}/></Field><Field label="Duration (minutes)"><input type="number" min={1} value={settings.schedule.duration} onChange={e=>setSchedule("duration",Number(e.target.value))}/></Field></div></Section>
 <Section icon={<LogIn size={21}/>} title="Student Login" description="Choose exactly one authentication method for this assessment."><div className="grid gap-4 md:grid-cols-2"><Choice active={settings.login.authentication==="PASSWORD"} title="Password Login" text="Registered email + common assessment password." onClick={()=>setSettings(s=>({...s,login:{authentication:"PASSWORD"}}))}/><Choice active={settings.login.authentication==="OTP"} title="OTP Login" text="Six-digit code sent through Brevo to the registered email." onClick={()=>setSettings(s=>({...s,login:{authentication:"OTP"}}))}/></div></Section>
 <Section icon={<Settings2 size={21}/>} title="Question Paper Rules" description="These controls are applied when a new attempt is generated."><div className="grid gap-4 md:grid-cols-2"><Toggle label="Randomize Questions" checked={settings.rules.randomQuestions} onChange={v=>setSettings(s=>({...s,rules:{...s.rules,randomQuestions:v}}))}/><Toggle label="Randomize Options" checked={settings.rules.randomOptions} onChange={v=>setSettings(s=>({...s,rules:{...s.rules,randomOptions:v}}))}/></div></Section>
 <Section icon={<RadioTower size={21}/>} title="Live Updates" description="Controls real-time refresh for the Live Monitor, Leaderboard and Analytics tabs."><Toggle label="Live dashboard updates" checked={settings.live.enabled} onChange={v=>setSettings(s=>({...s,live:{enabled:v}}))}/><p className="mt-3 text-xs text-slate-500">When OFF, manual Refresh still works. Turning it ON reconnects the real-time dashboard listeners.</p></Section>
 <Section icon={<Trophy size={21}/>} title="Results" description="Set the percentage required to pass."><Field label="Passing Percentage"><input type="number" min={0} max={100} step="0.01" value={settings.results.passingPercentage} onChange={e=>setSettings(s=>({...s,results:{passingPercentage:Number(e.target.value)}}))}/></Field></Section>
 <Section icon={<ShieldCheck size={21}/>} title="Security" description="Security behaviour remains enabled for the assessment platform."><div className="grid gap-4 md:grid-cols-2"><Info title="Fullscreen" text="The exam attempts to enter fullscreen when the test begins. A direct fullscreen exit is recorded as a security event."/><Info title="Security events" text="Suspicious activity is recorded and can automatically submit the attempt according to the assessment security policy."/><Info title="Auto submit" text="The server submits an expired attempt and records the reason, even if the student is no longer on the page."/><Info title="Admin controls" text="Force Submit is available from Live Monitor for active attempts."/></div></Section>
 </div>;
}
function Section({icon,title,description,children}:{icon:React.ReactNode;title:string;description:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-6 flex items-start gap-3"><div className="rounded-xl bg-slate-100 p-2 text-[#00629B]">{icon}</div><div><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-semibold text-slate-700">{label}<span className="mt-2 block">{children}</span></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between rounded-xl border p-4"><span className="font-medium text-slate-800">{label}</span><button type="button" onClick={()=>onChange(!checked)} aria-pressed={checked} className={`relative h-7 w-14 rounded-full transition ${checked?"bg-emerald-500":"bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked?"left-8":"left-1"}`}/></button></div>}
function Choice({active,title,text,onClick}:{active:boolean;title:string;text:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`rounded-xl border p-5 text-left ${active?"border-[#00629B] bg-blue-50 ring-2 ring-[#00629B]/10":"border-slate-200 hover:bg-slate-50"}`}><div className="flex items-center justify-between"><span className="font-semibold">{title}</span><span className={`h-4 w-4 rounded-full border-2 ${active?"border-[#00629B] bg-[#00629B]":"border-slate-300"}`}/></div><p className="mt-2 text-sm text-slate-500">{text}</p></button>}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold text-slate-800">{title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div>}
